name: Docker Build & Test (with Codex feedback)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build
        run: |
          docker build -t sonitranslate:test .

      - name: Test container
        if: success()
        run: |
          docker run -d --name sonitest -p 7860:7860 sonitranslate:test
          sleep 20
          curl -f http://localhost:7860/health || exit 1

      - name: Show logs if failed
        if: failure()
        run: docker logs sonitest || true

      - name: Upload logs to Codex
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-logs
          path: /home/runner/work/_temp/_github_workflow/**/*.log || ./logs || .

      - name: Notify Codex
        if: always()
        run: echo "::notice title=Codex::Build finished with status ${{ job.status }}"
