name: 🐳 Docker CI/CD - Auto Build & Test for SoniTranslate

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Проверяем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Кэш Docker слоёв
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4️⃣ Сборка Docker-образа
      - name: Build Docker image
        id: build
        run: |
          echo "🚧 Building Docker image..."
          docker build -t ghcr.io/${{ github.repository_owner }}/sonitranslate:latest . || {
            echo "❌ Docker build failed. Stopping workflow.";
            exit 1;
          }

      # 5️⃣ Проверяем, что образ собран
      - name: Verify image exists
        if: steps.build.outcome == 'success'
        run: |
          if ! docker image inspect ghcr.io/${{ github.repository_owner }}/sonitranslate:latest >/dev/null 2>&1; then
            echo "❌ Docker image not found after build!"
            exit 1
          fi
          echo "✅ Docker image built successfully!"

      # 6️⃣ Запускаем контейнер для тестов
      - name: Run container
        if: steps.build.outcome == 'success'
        run: |
          echo "🚀 Running test container..."
          docker run -d -p 7860:7860 --name sonitranslate ghcr.io/${{ github.repository_owner }}/sonitranslate:latest
          sleep 40
          docker ps -a

      # 7️⃣ Проверка API (endpoint /health)
      - name: Check API health
        if: steps.build.outcome == 'success'
        run: |
          echo "🧪 Checking API health..."
          if ! curl -fs http://localhost:7860/health; then
            echo "❌ API endpoint not responding!"
            docker logs sonitranslate
            exit 1
          fi
          echo "✅ API is healthy!"

      # 8️⃣ Авторизация в GHCR
      - name: Log in to GitHub Container Registry
        if: steps.build.outcome == 'success'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 9️⃣ Публикация образа в GHCR
      - name: Push Docker image
        if: steps.build.outcome == 'success'
        run: |
          echo "📦 Pushing image to GHCR..."
          docker push ghcr.io/${{ github.repository_owner }}/sonitranslate:latest
          echo "✅ Image pushed successfully!"

      # 🔟 Показываем логи, если что-то упало
      - name: Show container logs on failure
        if: failure()
        run: |
          echo "📜 Showing container logs..."
          docker logs sonitranslate || true

      # 1️⃣1️⃣ SSH Debug (по желанию)
      - name: Debug via SSH (optional)
        if: failure()
        uses: mxschmitt/action-tmate@v3

      # 1️⃣2️⃣ Очистка после выполнения
      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up..."
          docker rm -f sonitranslate || true
          docker image prune -f
