name: 🐳 Docker CI/CD - Auto Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Кэш Docker-слоёв
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4️⃣ Собираем Docker-образ
      - name: Build Docker image
        id: build
        run: |
          echo "🚧 Building Docker image..."
          docker build -t ghcr.io/${{ github.repository_owner }}/sonitranslate:latest .

      # 5️⃣ Запуск контейнера для тестов
      - name: Run container
        if: success() && steps.build.outcome == 'success'
        run: |
          echo "🚀 Running test container..."
          docker run -d -p 7860:7860 --name sonitranslate ghcr.io/${{ github.repository_owner }}/sonitranslate:latest
          sleep 45
          docker ps

      # 6️⃣ Проверка API (healthcheck)
      - name: Check API health
        if: success() && steps.build.outcome == 'success'
        run: |
          echo "🧪 Checking /health endpoint..."
          curl -f http://localhost:7860/health || (echo "❌ API not responding" && docker logs sonitranslate && exit 1)

      # 7️⃣ Загрузка образа в GHCR
      - name: Log in to GitHub Container Registry
        if: success() && steps.build.outcome == 'success'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: success() && steps.build.outcome == 'success'
        run: |
          echo "📦 Pushing image to GHCR..."
          docker push ghcr.io/${{ github.repository_owner }}/sonitranslate:latest

      # 8️⃣ Показываем логи, если что-то пошло не так
      - name: Show container logs on failure
        if: failure()
        run: docker logs sonitranslate || true

      # 9️⃣ (опционально) Отладка через SSH
      - name: Debug via SSH
        if: failure()
        uses: mxschmitt/action-tmate@v3

      # 🔟 Очистка
      - name: Cleanup
        if: always()
        run: |
          docker rm -f sonitranslate || true
          docker image prune -f
